### ISSUE TITLE
如何导出数据？

### ISSUE THREAD

**Issue by JasonkayZK** [telppa/KMCounter#1]
软件很轻量级，点个赞。
不过想问一下，能否把统计里面的数据按日或者小时导出呢？

**Comment by telppa** [comment]
数据都保存在 KMCounter.ini 里 。
只存了以天为单位，最近30天的数据，所以天为单位的数据可以直接用。
改小时需要自己改代码。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/KMCounter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月16日(星期二) 下午5:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/KMCounter] 如何导出数据？ (#1)





 
软件很轻量级，点个赞。
 不过想问一下，能否把统计里面的数据按日或者小时导出呢？

**Comment by JasonkayZK** [comment]
我是今天刚刚下载使用的，为什么没有找到这个KMCounter.ini文件呢？

**Comment by telppa** [comment]
我强迫症，用的固态硬盘，为了尽量减少写硬盘的次数，所以只在退出程序或者关机时才保存数据…… 虽然数据才几k……




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月16日(星期二) 下午5:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [telppa/KMCounter] 如何导出数据？ (#1)





 
我是今天刚刚下载使用的，为什么没有找到这个KMCounter.ini文件呢？

**Comment by JasonkayZK** [comment]
好的，明白了，谢谢！
