### ISSUE TITLE
请问我下载的ahk源码版本，无法运行

### ISSUE THREAD

**Issue by ghost** [telppa/KMCounter#12]
请问我下载的ahk源码来运行的，源码的最后#Inculde <OSDTIP> 几个似乎引用不到？

**Comment by ghost** [comment]
缺少了Lib包，请问可以补上吗~

**Comment by telppa** [comment]
你去 autoahk 的那个帖子里看看，我在里面列明了需要自己补充哪些库，或者直接运行 exe。

**Comment by ghost** [comment]
谢谢~  已补齐~
