### ISSUE TITLE
鼠标点击热力图啥时候做出来呀？

### ISSUE THREAD

**Issue by jqrxjk** [telppa/KMCounter#16]
这个功能可太有意思了，作者千万别因为感觉需求的人不多就不做了呀，想要知道鼠标点击情况的人本来就是少数，或者他们根本就没意识到还有鼠标点击热力图这个功能而已，只要做得好，喜欢的人肯定多。

**Comment by telppa** [comment]
鼠标热力图就看着好玩，没啥硬需求，而且要搞很久去了，所以算了。
