### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zszczh** [telppa/KMCounter#17]
![2022-05-04_234316](https://user-images.githubusercontent.com/30950457/166719238-6b1e7b19-26f5-4111-a7d8-e4ed6f714252.png)

**Comment by telppa** [comment]
要运行源码的话，自己找找相关库文件（autoahk.com 或 autohotkey.com），或者运行exe版的。

**Comment by zszczh** [comment]
谢谢大佬。昨天我在从GitHub下载的压缩包里没找的exe文件，就只好用源码运行。你给出的蓝奏云我昨天试了应该有四遍，都进不去。刚刚看你说有exe，我就猜是不是在蓝奏云，这试到第三遍出来了。

**Comment by telppa** [comment]
github上面几乎所有项目，右边的release里面放出来的都是编译好的（可以直接运行的）。
