### ISSUE TITLE
建议 显示累计所有天数的键盘热力图

### ISSUE THREAD

**Issue by stars-one** [telppa/KMCounter#19]
好像只能查看当天的键盘热力图，没法查看累计所有天数的热力图，可以加个开关来显示所有天数的键盘热力图

**Comment by Egg12138** [comment]
在ShowHeatMap()中可以修改，然后自行编译就可以

**Comment by xzzdys** [comment]
去读了源码，发现是可以显示的
按方向键可以选择显示哪一天的分布，选择成明天就会显示总和

**Comment by Egg12138** [comment]
> 去读了源码，发现是可以显示的 按方向键可以选择显示哪一天的分布，选择成明天就会显示总和

还真是，之前没看仔细
