### ISSUE TITLE
Some suggestions on setting panel

### ISSUE THREAD

**Issue by abc1044** [telppa/KMCounter#2]
- In the screen size column, it is recommended to **add explanatory information**, such as calculating the mouse movement distance.
- In the function of setting the real size, **add inches and screen ratio options**, such as 24 inches, 16:9, this kind. (Most people may know the screen size, but don’t know the specific length and width)
- Do you consider increasing the support of moving distance for **multiple screens,** or how to set it up.

**Comment by telppa** [comment]
The first line is the mouse movement distance (in meters)


I used a more convenient method to get the screen size automatically, without having to set it manually. However, this method can be inaccurate in a few cases, so a separate setting is provided.


If you multiple monitors are the same size, then still get accurate data, not plan to provide multi-monitor support for different sizes for now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/KMCounter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 上午9:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/KMCounter] Some suggestions on setting panel (#2)





  
In the screen size column, it is recommended to add explanatory information, such as calculating the mouse movement distance.
 
In the function of setting the real size, add inches and screen ratio options, such as 24 inches, 16:9, this kind. (Most people may know the screen size, but don’t know the specific length and width)
 
Do you consider increasing the support of moving distance for multiple screens, or how to set it up.

**Comment by abc1044** [comment]
Well, thank you for your reply. Add some explanatory text to make it clearer for users. I am a multi-screen user, and the resolution and size are different...So I mentioned the multi-screen situation, it doesn't matter if you don't support the plan.
Anyway, thank you very much for your software, **it's great**.
