### ISSUE TITLE
请问一下这个 按键记录存在什么地方的呢

### ISSUE THREAD

**Issue by shoaly** [telppa/KMCounter#3]
还是说 这个记录是每日刷新的

**Comment by telppa** [comment]
退出程序 或关机时 或者新的一天凌晨 ，这三种情况会自动保存一次数据。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/KMCounter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 中午1:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/KMCounter] 请问一下这个 按键记录存在什么地方的呢 (#3)





 
还是说 这个记录是每日刷新的
