### ISSUE TITLE
Chrome download v3.5 failed, indicating that there is a virus

### ISSUE THREAD

**Issue by abc1044** [telppa/KMCounter#5]
When Chrome downloads the latest KMCounter.v3.5.zip file, it prompts that it contains a virus and the download fails. 
Feedback this situation to you, how to solve it.

**Comment by abc1044** [comment]
![Uploading image.png…]()

**Comment by abc1044** [comment]
![image](https://user-images.githubusercontent.com/18114052/111862480-88e5f580-8990-11eb-9142-322372885602.png)

**Comment by telppa** [comment]
I can do nothing.

**Comment by abc1044** [comment]
Well, I found the reason. As mentioned in the description, it was blocked by windows defender. When I turn off the real-time protection function of windows defender, it works.
