### ISSUE TITLE
大佬您好，第一次使用ahk，这里启动报错，能简单提示下嘛

### ISSUE THREAD

**Issue by hxpeng123** [telppa/KMCounter#8]
![image](https://user-images.githubusercontent.com/39463106/114508394-e2c39d80-9c66-11eb-9d03-8bedf56ff6ed.png)
在AutoHotkey官网下载之后，点击脚本就弹出这个来了

**Comment by telppa** [comment]
https://www.autoahk.com/archives/35147


这里有解答，我直接贴过来吧。


------------------------------------------------------------------------------------------
如何以源码方式运行



因为这是一个同时面向 ahk 用户与非 ahk 用户的项目，所以我只提供编译好的版本下载。

如果你需要以源码方式运行，请自行去 github 下载源码，并补齐以下库文件。

#Include <OSDTIP&gt;

#Include <Class_CtlColors&gt;

#Include <Class_ImageButton&gt;

#Include <UseGDIP&gt;

#Include <BTT&gt;

#Include <Gdip&gt;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "telppa/KMCounter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 下午2:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[telppa/KMCounter] 大佬您好，第一次使用ahk，这里启动报错，能简单提示下嘛 (#8)





 

 在AutoHotkey官网下载之后，点击脚本就弹出这个来了

**Comment by hxpeng123** [comment]
非常感谢，我下载错了，下了源代码的方式， 用编译好的完美运行
